коррекция
hmzxpDev/advancedJavaScript pull request #3
Opened 2021-05-02 11:19 UTC by hmzxpDevop

исправил total price, добавил возможность сразу выбрать размера бургера при создании объекта

2021-05-06 14:20 UTC, Om1X requested changes

2021-05-06 14:20 UTC, Om1X commented on Урок 3. Асинхронные запросы/Домашнее задание/2. Добавьте в соответствующие классы методы добавления товара в корзину, удаления товара из корзины и получения списка товаров корзины/js/main.js
> +    this.totalPrice = 0;
убираем, для подсчета суммы нужен метод, который посчитает и вернет значение. Хранить не нужно это значение.

2021-05-06 14:20 UTC, Om1X commented on Урок 3. Асинхронные запросы/Домашнее задание/2. Добавьте в соответствующие классы методы добавления товара в корзину, удаления товара из корзины и получения списка товаров корзины/js/main.js
> +    buttonAddRemove();
плохое решение. Клики лучше делегировать на общем для товаров блоке, чтобы не плодить 100500 однотипных обработчиков

2021-05-06 14:20 UTC, Om1X commented on Урок 3. Асинхронные запросы/Домашнее задание/2. Добавьте в соответствующие классы методы добавления товара в корзину, удаления товара из корзины и получения списка товаров корзины/js/main.js
> +    totalPriceUpdate(this.totalPrice);
не имеет смысла, с учетом замечаний выше

2021-05-06 14:20 UTC, Om1X commented on Урок 3. Асинхронные запросы/Домашнее задание/2. Добавьте в соответствующие классы методы добавления товара в корзину, удаления товара из корзины и получения списка товаров корзины/js/main.js
> +    fetch(`${API}/addToBasket.json`)
запрос нужно слать первым, а потом уже актуализировать фронт

2021-05-06 14:20 UTC, Om1X commented on Урок 3. Асинхронные запросы/Домашнее задание/2. Добавьте в соответствующие классы методы добавления товара в корзину, удаления товара из корзины и получения списка товаров корзины/js/main.js
> +  itemRemove(itemID, button) {
тут аналогичные замечания

2021-05-06 14:20 UTC, Om1X commented on Урок 3. Асинхронные запросы/Домашнее задание/2. Добавьте в соответствующие классы методы добавления товара в корзину, удаления товара из корзины и получения списка товаров корзины/js/main.js
> +}
Так делать плохо. Вся логика должна быть исключительно внутри классов

2021-05-19 22:29 UTC, Om1X requested changes

2021-05-19 22:29 UTC, Om1X commented on Урок 3. Асинхронные запросы/Домашнее задание/2. Добавьте в соответствующие классы методы добавления товара в корзину, удаления товара из корзины и получения списка товаров корзины/js/main.js
> +    });
Здесь лучше оптимизировать через делегирование событий, т.к. в данном случае получается очень много однотипных обработчиков, здесь вполне можно обойтись тремя обработчиками для каждого из кейсов. Нужно будет только грамотно отфильтровать клики

2021-05-19 22:29 UTC, Om1X commented on Урок 3. Асинхронные запросы/Домашнее задание/2. Добавьте в соответствующие классы методы добавления товара в корзину, удаления товара из корзины и получения списка товаров корзины/js/main.js
> +    });
Также стоит сделать обращение к корзине через this.basket а не через глобальную переменную basket

2021-05-19 22:52 UTC, Om1X requested changes

2021-05-19 22:52 UTC, Om1X commented on Урок 5. Фреймворк Vue.js/домашка/project/js/main.js
> +      let text = this.searchLine.toLowerCase().trim();
у нас была регулярка для поиска, ее и нужно было использовать

2021-05-19 22:52 UTC, Om1X commented on Урок 5. Фреймворк Vue.js/домашка/project/js/main.js
> +        this.filteredProducts = this.products.filter((el) => { //создаёт новый массив со всеми элементами, прошедшими проверку, задаваемую в передаваемой функции.
this.products.filter итак вернет все товары, если поисковая строка будет пустая

2021-05-19 22:52 UTC, Om1X commented on Урок 6. Компоненты Vue.js/Домашка/project/index.html
> +        <app-search></app-search>
куда пропали вынесенные на уроке компоненты каталога и корзины?

2021-05-19 22:52 UTC, Om1X commented on Урок 6. Компоненты Vue.js/Домашка/project/js/main.js
> +})
компонент должен был содержать разметку, поисковую строку в data и по клику / сабмиту через $root.$refs.catalog вызывать метод поиска, передавая поисковую строку

2021-05-21 16:28 UTC, hmzxpDevop commented on Урок 6. Компоненты Vue.js/Домашка/project/index.html
> +        <app-search></app-search>
не понял комментарий

2021-07-21 17:09 UTC, Om1X requested changes

2021-07-21 17:09 UTC, Om1X commented on Урок 7. JavaScript на сервере/домашка/project_express_single/public/js/CartComp.js
> +                this.$parent.putJson(`/api/cart/${item.id_product}`, { quantity: -1 });
`item.quantity--;` нужно выполнять по результатам `this.$parent.putJson(`/api/cart/${item.id_product}`, { quantity: -1 });` иначе данные могут разойтись

2021-07-21 17:09 UTC, Om1X commented on Урок 7. JavaScript на сервере/домашка/project_express_single/public/js/CartComp.js
> +                this.cartItems.splice(this.cartItems.indexOf(item), 1)
здесь тоже

2021-10-19 18:03 UTC, merged